### ISSUE TITLE
Cryptoeconomics solutions for SOB state-change gas requirement

### ISSUE THREAD

**Issue by 3esmit** [status-im/ideas#17]
## Preamble

    Idea: <to be assigned>
    Title: Cryptoeconomics solutions for SOB public adoption
    Status: Draft
    Created: 2017-11-14

## Summary
Surround SOB state-change with cryptoeconomics incentives using bounty prize to pay deploy. 

## Vision
Status Open Bounty gas expanses are currently being paid by Status, this is done because repository owners without any Ether can start opening bounties. 
Status will not be able to pay for this service forever, however we replace it by a cryptoeconomic solution around the state-change of SOB. 
The simpliest implementation would be: 
- at first donation, whatever is ERC20 or ETH, the first donator will pay for the bounty initialization; 
- and the bounty winners pay for their withdraw;
- - or makes a signed message allowing other to make the withdraw to his account by giving some part of the prize to pay gas cost + incentive.

## Swarm Participants

- Smart Contracts:  @3esmit
- SOB Lead: 
- Review: @andytudhope
- Testing & Evaluation:  

### Minimum Viable Product

Goal Date:  
Description: 

### Iteration 1..N
Goal Date:  
Description: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by andytudhope** [comment]
I'd quite like to help out with this (perhaps with a friend if I can convince him). I think we should be using the registry not just to whitelist tokens for bounties, but also to get around the manual whitelist for organizations we are using right now.
Essentially, the basic idea here would be - allow only, say, 50 open bounties per owner at a given time. If someone wanted to open more than that, I think we can trust that they know a fair bit about Ethereum or are scriptkiddies. Therefore, addresses who want to have more than 50 open bounties at a given time can pay a fee in SNT to get into the registry and any address in that registry can deploy a number of issues relative to the amount of SNT they have deposited. I reckon it would be best to burn the SNT, rather than holding it or otherwise distributing it, as this will - theoretically at least - increase the value of the other SNT still in circulation and provide an important sink for the tokens: vitalik.ca/general/2017/10/17/moe.html
It's worth noting that this doesn't solve the gas problem we're facing, but I feel strongly that Status should just foot the gas bill to make it as easy-to-use as possible, especially for other OSS projects that don't know anything about Ethereum. We could reimburse ourselves with SNT deposits paid to the curated registry, but I think it better to burn that as a gift to the community.

"Burn, burn with me love, to hell with decay!
To live is to live and, while alive, to die anyway"
-- Andrei Voznesenski

**Comment by jacqueswww** [comment]
@andytudhope @3esmit I am still brainstorming this one. But yes in a normal token contract scenario: the initializer pays for setup, bounty winner pays for withdrawing. This also eliminates the risk of locking contracts, where for some reason not enough gas is estimated initially. Could we not rather focus on education of users new to ethereum ? The right question mark in the UI could easily help a new user to understand how this works (on the Manage Payouts screen for example).

**Comment by jacqueswww** [comment]
One can always faucet the +/- gas price to them on the first payout as well :smile: since one has their payout address that the would call `withdraw` from. (And we only do this for the first bounty retrieved).

**Comment by 3esmit** [comment]
I agree with education of users, but we should make the UX simpliest possible and avoid ethereum transactions as most as possible, although they are inevitable at some point. 
We still would require that repo-owners enable their repositories upon defining one or more ethereum addresses to sign (offchain) messages allowing withdraw. 
Issues should not necessarily be marked as bounty, but all are open for bounties as long they receive any bounty, the bot could then do the reverse and label it as bounty, if authorization for that is given. 
For that, a single contract can be used, or multiple (to keep one address per issue).

**Comment by arash009** [comment]
I strongly agree with the user education. We need to strike a balance between not over complicating it for those that are new to the crypto world, but I think we also have a duty to help develop their understanding - if they are trying to use our platform, assumption is they are interested in the space and want to learn more.

I also dont think we want to complicate it too much, at least not at first. If we can find an easy way to move the gas cost for the execution of the contract to the repo owner at the time of posting, and even to them at the time of bounty winner withdrawing, would be a good start (it would be the cost of doing business, which is still very minimal considering alternatives)

**Comment by naghdy** [comment]
Closing this as its gone stale. Feel free to re-open if its still relevant or if there is someone working on it.
