### ISSUE TITLE
Status Token Registry: Default Supported Tokens for Status Wallet

### ISSUE THREAD

**Issue by 3esmit** [status-im/ideas#18]
## Preamble

    Idea: <to be assigned>
    Title: Status Token Registry
    Status: Draft  
    Created: 2014-11-12  
    Required by: #3 

## Summary
Create a Token Registry owned by SNT holders

## Vision
Token Registries may get bloated with worthless tokens, leading to high processing in wallet load, to solve this, a Token Registry controlled by SNT holders would be deployed for use in #3 , where the addition of tokens would only happen upon approval of a SNT holders quorum. Any change on the registry should also happen upon SNT holders quorum. 
To incentive SNT holders to accept a registry, the registrant can place a bribe to distribute among all yes-voters and Status Network reserve. 

## Swarm Participants

- Smart Contracts:  @3esmit
- Wallet integration:
- SOB integration: 
- Testing & Evaluation: 
- Review: 

### Minimum Viable Product

Goal Date:  
Description: 

### Iteration 1..N
Goal Date:  
Description: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by andytudhope** [comment]
I'd quite like to help out with this (perhaps with a friend if I can convince him). I think we should be using the registry not just to whitelist tokens for bounties, but also to get around the manual whitelist for organizations we are using right now.
Essentially, the basic idea here would be - allow only, say, 50 open bounties per owner at a given time. If someone wanted to open more than that, I think we can trust that they know a fair bit about Ethereum or are scriptkiddies. Therefore, addresses who want to have more than 50 open bounties at a given time can pay a fee in SNT to get into the registry and any address in that registry can deploy a number of issues relative to the amount of SNT they have deposited. I reckon it would be best to burn the SNT, rather than holding it or otherwise distributing it, as this will - theoretically at least - increase the value of the other SNT still in circulation and provide an important sink for the tokens: vitalik.ca/general/2017/10/17/moe.html
It's worth noting that this doesn't solve the gas problem we're facing, but I feel strongly that Status should just foot the gas bill to make it as easy-to-use as possible, especially for other OSS projects that don't know anything about Ethereum. We could reimburse ourselves with SNT deposits paid to the curated registry, but I think it better to burn that as a gift to the community. 

"Burn, burn with me love, to hell with decay! 
To live is to live and, while alive, to die anyway"
-- Andrei Voznesenski

**Comment by jacqueswww** [comment]
This might be a perfect incentive to burn some SNT, what do you think ? Allowing all tokens going to getting tokens listed on the registry to be burned.

**Comment by andytudhope** [comment]
Yes! This is what I've been advocating for some time. "Burn, burn with me love" ;)

**Comment by jacqueswww** [comment]
Well the idea of bribes and community voting could still remain, this would just be an initial listing fee (I'd prefer it being pegged to usd). I remember paying 5 or 10 usd to get a chrome extension on the web store for example - it's quite a common strategy it seems ;)

**Comment by 3esmit** [comment]
There is no  fixed "fee" to register, instead a faculty "bribe" can be placed with the request. 

This bribe is divided by half, where half is divided in between who voted (no matter if yes or no).
The other half, in case approved is sent to a Locker Reserve, in case of disapproved is returned back to requester.  
The Funds in locker are available to Status Network and may be used in Future.

Editing a registry is possible, but will fall into democratic vote again, with a possible "bribe" incentive. The request to edit must come only from registrant, but the registrant should be able to forcefully changed by SNT democratic vote through a "curator delegate topic".

**Comment by 3esmit** [comment]
We could use 0xProject Token Registry, as they are our parteners, or make it user-selectable if want Status Token Registry or 0xProject, as they will be ABI-compatible in between each other, as following https://github.com/ethereum/EIPs/issues/22

**Comment by naghdy** [comment]
Closing this as its gone stale. Feel free to re-open if its still relevant or if there is someone working on it.

**Comment by 3esmit** [comment]
@andytudhope Are you working on this?
