### ISSUE TITLE
Gas economic abstraction in top of smart contracts

### ISSUE THREAD

**Issue by 3esmit** [status-im/ideas#73]
## Preamble

    Idea: 73
    Title: Use SNT as gas in SNT transactions
    Status: Draft
    Created: 2018-02-01

## Summary
Enable gas economic abstraction for users being able to only hold SNT for interacting with Status Network.
An offchain whisper message, containg an ethereum signed message (and its payload) that is accepted by a smart contract that costs ETH gas to be run, but the contract calculates the gas used and pays back msg.sender in user's signed message specified token and gas price.

## Swarm Participants

- Lead Contributor:  @3esmit
- UX: @alexvandesande 
- Contributor/Testing @iurimatias 
- Contributor/Testing: @richard-ramos 

## Product Overview

A barrier for user adoption to blockchain through Status would be the need of managing two tokens for paying fees, ether gas for moving the [SNT](https://etherscan.io/address/0x744d70fdbe2ba4cf95131626614a1763df805b9e#readContract) fee from user balance to decentralized service provider. 
The product solve this by emulating a gas abstraction in top by adding "Gas Relayer Actor" in top of smart contracts as: [Identity](https://github.com/status-im/contracts/blob/73-economic-abstraction/contracts/identity/Identity.sol)[GasRelay](https://github.com/status-im/contracts/blob/73-economic-abstraction/contracts/identity/IdentityGasRelay.sol), MultiSigWallet, [SNTController ](https://github.com/status-im/contracts/blob/73-economic-abstraction/contracts/status/SNTController.sol#L82)(updated from SNTPlaceHolder); 

### Product Description

- Allows SNT holder to broadcast ethereum signed messages to anyone with ETH to validate them in the GasRelay smart contracts, and offering a refund of gas used in a gas price set in SNT. 
- Whoever have ether could verify if the gas price worth the SNT gas price offered.
- This becomes a micro trade of ETH->SNT.
- Allow user to use any token they want (even ETH, or ETH stored in Identity).

### Minimum Viable Product

1. Identity Gas Relay
Goal Date:  
Description: 
a. Gas Relay Node that recieve whisper messages from Identity owners, 
b. Identity User Interface with Gas Relayed option of calls

2. SNT Gas Relayer
Goal Date:  
Description: 
a. Gas Relay Node implements watching messages for SNTController 
b. User interface for creating Identity+ENS register (pay gas in SNT)
c. Moving SNT to other address from SNTController terms (paying gas in SNT)

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by iurimatias** [comment]
For information purposes here is an (old) implementation of this idea https://github.com/iurimatias/TransactionRelay

**Comment by alexvandesande** [comment]
I've been discussing this with @3esmit for a while now and I'd like to share what I see could be a potential UI that any ethereum app could share for login/signup

The app creates a local ethereum account automatically. That account never needs to leave the device and since it will not contain ether, backing up can be optional.

<img width="366" alt="screen shot 2018-03-23 at 4 02 52 pm" src="https://user-images.githubusercontent.com/112898/37848666-aedcc290-2eb3-11e8-96a8-9c4510c3f7a7.png">

The user starts by typing a name of their ID, or the one they want

<img width="433" alt="screen shot 2018-03-23 at 4 06 12 pm" src="https://user-images.githubusercontent.com/112898/37848828-4a3676a0-2eb4-11e8-934d-26a9a6e357ee.png">

If the name doesn't exist then the user will create one (this might have a cost)

<img width="429" alt="screen shot 2018-03-23 at 4 06 09 pm" src="https://user-images.githubusercontent.com/112898/37848809-356d7926-2eb4-11e8-9846-6cbd4643ec10.png">
 
If the name exists, then it allows you to connect to it by confirming on another device.

<img width="341" alt="screen shot 2018-03-22 at 12 47 59 pm" src="https://user-images.githubusercontent.com/112898/37848865-6265e81e-2eb4-11e8-9395-a7bdff660cfb.png">

Connecting means you either send a whisper message or you show a transaction that needs to be executed by some owner of the identity

<img width="342" alt="screen shot 2018-03-22 at 12 48 07 pm" src="https://user-images.githubusercontent.com/112898/37848928-9661bce2-2eb4-11e8-8ded-44832fc0e157.png">

The other device receives a notice asking a confirmation to connect.

Done!

What do we solve?

* Universal human readable login for ethereum 
* ID protected by multi signatures in many devices
* Each individual device doesn't need to own ether, instead it only holds a key

**Comment by martinklepsch** [comment]
You're probably aware of this already but I figured I'd leave this here for context https://gastoken.io

**Comment by 3esmit** [comment]
Thanks, @martinklepsch .
Their project is a different thing, they are "hacking" EVM properties of clear storage that give negative gas. You pay to put junk in blockchain and later you clear it because they cost negative gas, and then you can pay less gas in a transaction (and maybe extend the block gas limit of a transaction, not sure) 

This projects enables users making transactions and paying any ERC20 as gasPrice. 

So gasToken would be able to be used as payment or being called by Identity, however the property of increasing gas when burned would be implemented outside. The called contract that would than burn this token when instructed.
I'm planning to do modular extensions to Identity, so maybe it would be possible that we have a plugin, such as "gasTokenBurnAndCallGasRelay".

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
