### ISSUE TITLE
Restore Contacts and Account Info

### ISSUE THREAD

**Issue by mandrigin** [status-im/ideas#84]
## Preamble

    Idea: 84
    Title: Restore Contacts and Account Info
    Status: Draft
    Created: 2018-02-20
    Requires (*optional): <Idea number(s)>
    Replaces (*optional): <Idea number(s)>

## Summary
As a user, when restoring an account I want to see restored:
- my username;
- my contacts list;
- my userpic (if possible).

## Swarm Participants
- Lead Contributor: @mandrigin
- Testing & Evaluation: 
- Contributor (Go): @adriacidre, 20h
- Contributor (Go): @pilu, 20h
- Contributor: 
- PM: 
- UX (if relevant): 

### Product Description
We can use Swarm and Status Cluster to store this information and encrypt them with a public key of an account for privacy reasons.

### Minimum Viable Product

Goal Date:  

Restore username when the app is uninstalled and re-installed again.

Description: 
1. Provide API from `status-go` to save/restore profile data (implement web3 `bzz_*` APIs).
2. Use this API from the react UI.
3. Use HTTP API for Swarm and Status Cluster as a proxy.

## Dates
Goal Date:  

Description: 

Testing Days required: 

## Success Metrics
7 day retention rate for the users who restored the account is > 70%

## Exit criteria
Re-installing the app keeps your contacts, profile picture and username

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by JekaMas** [comment]
Related to https://github.com/status-im/status-go/issues/661
@feuGeneA @yenda

**Comment by pilu** [comment]
The swarm team is planning the light client development for Q2

https://github.com/ethersphere/swarm/wiki/Light-mode-of-operation

For now I think the only thing we can do is proxying the call to our cluster, since other services like infura don't support swarm (yet?). 

So one thing to do is adding the swarm node in our cluster and start testing it.
I tried different things in local and it was working pretty nice, even if sometimes the propagation was pretty slow (5/10 minutes), but it shouldn't be a problem for this specific case.

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
