### ISSUE TITLE
Automated upgrade testing

### ISSUE THREAD

**Issue by antdanchenko** [status-im/ideas#98]
## Preamble

    Idea: 98
    Title: Automated upgrade testing
    Status: Draft
    Created: 2018-03-21

## Swarm Participants

- Lead Contributor: 
- Testing & Evaluation: 
- Contributor: 
- Contributor: 
- PM: 
- UX (if relevant): 

### Minimum Viable Product

Goal Date:  

Description: 

## Dates
Goal Date:  

Description: 

Testing Days required: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by lukaszfryc** [comment]
As we've talked before @antdanchenko, I'd definitely want to help with the upgrade testing.

Few things I have have on my mind:

1. We could use headless Status client to generate test data on for account instead of doing it on the UI level

I've already researched @mandrigin's https://github.com/mandrigin/status-go-bots and #3543 that could help with it. There is also #91 (Extended E2E tests for message reliability) that will probably need such tool.  
 
2. Our MVP could be a simple scenario where a previous version of Status is installed, account is created and then the app is upgraded to the new version. In the MVP we would not populate the account with messages, etc

Looks like Appium already supports additional parameters while installing the app https://github.com/appium/appium/issues/3377.

**Comment by therussiankid92** [comment]
Hi there,

I've been trying to use the additional parameters, but I think somehow selenium still expects that installApp is called with only the path, and not the options. 

More info here: https://github.com/appium/appium/issues/10487

Let me know how if this helps and if you find a workaround.

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
